= SIRA
:hardbreaks:
:imagesdir: ./

== Requirements
Python 2.7
npm
Docker

[[work-env]]
== Install work environment
If virtualenv is not installed
`pip install virtualenv`

Create virtualenv
`virtualenv venv`

Install pipeline dependencies
`npm install -g node-sass postcss-cli autoprefixer`

Install dependencies
`pip install -r requirements.txt`

[[activate-venv]]
== Activate venv
Do <<work-env>>
`source venv/bin/activate`

== Launch locally
Do <<activate-venv>>
Ensure `local_launch.sh` and `launch.sh` have execution rights
`fab local_launch`

Deployed on `http://127.0.0.1:8000/`
Admin page accessible at `http://127.0.0.1:8000/admin/`

== Updating the migration files
Do <<activate-venv>>
`python manage.py dumpdata -e wagtailcore.groupcollectionpermission -e auth.permission -e contenttypes.contenttype -e wagtailimages.image -e sessions.session -e auth.group -e auth.user -e wagtailcore.grouppagepermission --natural-foreign --indent 2 > sira/fixtures/sira.json`

[[build-image]]
== Build SIRA dev docker image
Do <<aliases>>
`build_image dev 1.1` env followed by docker image version

== Launch docker-compose locally
`fab local_docker_compose:$version_git_tag_name`

== Launch tests
`python manage.py test`


== Deploy
Install the deployment environment
`fab init_tools:pwd=changeme -H sudo_user@deployment_host_ip:deployment_host_ssh_port`

Install the images (avoid it when working on a remote VM because it may be way too slow)
`fab install_docker_images -H devops@deployment_host_ip:deployment_host_ssh_port`

Deploy and launch
`fab deploy:version=0.2,postgres_user=admin,postgres_password=changeme,env=dev,include_media=True -H devops@deployment_host_ip:deployment_host_ssh_port`
