#!/bin/sh

sudo apt-get update

# git
sudo apt-get install -y git

# docker
# prerequisites
sudo apt-get update
sudo apt-get install -y apt-transport-https ca-certificates
sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
sudo chmod 646 /etc/apt/sources.list.d/docker.list
sudo echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" > /etc/apt/sources.list.d/docker.list
sudo chmod 644 /etc/apt/sources.list.d/docker.list
sudo apt-get update
sudo apt-get purge lxc-docker
apt-cache policy docker-engine
sudo apt-get update
sudo apt-get install -y linux-image-extra-$(uname -r) linux-image-extra-virtual
# actual install
sudo apt-get update
sudo apt-get install -y docker-engine
sudo service docker start
# test install
sudo docker run hello-world
# install docker-compose
curl -L https://github.com/docker/compose/releases/download/1.8.1/docker-compose-`uname -s`-`uname -m` > docker-compose
sudo mv docker-compose /usr/local/bin/
sudo chmod 711 /usr/local/bin/docker-compose
sudo chown vagrant:docker /usr/local/bin/docker-compose
# add user to docker group to avoid using sudo
sudo groupadd docker
sudo usermod -aG docker $USER
logout
