# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-25 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sira', '0004_imagepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videopage',
            options={'verbose_name': 'Videos'},
        ),
    ]
